// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kqrjkwersomkdprdxgxj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtxcmprd2Vyc29ta2RwcmR4Z3hqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NTUyMzUsImV4cCI6MjA3MDEzMTIzNX0.sn2cCS0wiqD5lPHMXEp5wn2-d484eOqGkSrQHWZ9XJI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});